export const LOGIN = "LOGIN/LOGIN";
export const LOGIN_SUCCESS = "LOGIN/LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN/LOGIN_ERROR";

export const REGISTER = "LOGIN/REGISTER";
export const REGISTER_SUCCESS = "LOGIN/REGISTER_SUCCESS";
export const REGISTER_ERROR = "LOGIN/REGISTER_ERROR";

export const LOGOUT = "LOGIN/LOGOUT";

export const GET_PROFILE = "CHAT/GET_PROFILE";
export const GET_PROFILE_SUCCESS = "CHAT/GET_PROFILE_SUCCESS";

export const GET_CONVERSATIONS = "CHAT/GET_CONVERSATION";
export const GET_CONVERSATIONS_SUCCESS = "CHAT/GET_CONVERSATION_SUCCESS";

export const BLOCK_USER = "CHAT/BLOCK_USER";
export const BLOCK_USER_SUCCESS = "CHAT/BLOCK_USER_SUCCESS";

export const UNBLOCK_USER = "USER/UNBLOCK_USER";
export const UNBLOCK_USER_SUCCESS = "USER/UNBLOCK_USER_SUCCESS";

export const CREATE_CONVERSATION = "CHAT/CREATE_CONVERSATION";
export const CREATE_CONVERSATION_SUCCESS = "CHAT/CREATE_CONVERSATION_SUCCESS";

export const CREATE_GROUP = "CHAT/CREATE_GROUP";
export const CREATE_GROUP_SUCCESS = "CHAT/CREATE_GROUP_SUCCESS";

export const UPDATE_AVATAR = "CHAT/UPDATE_AVATAR";
export const UPDATE_AVATAR_SUCCESS = "CHAT/UPDATE_AVATAR_SUCCESS";

export const UPDATE_PROFILE = "CHAT/UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "CHAT/UPDATE_PROFILE_SUCCESS";

export const UPDATE_GROUP_IMAGE = "CHAT/UPDATE_GROUP_IMAGE";
export const UPDATE_GROUP_IMAGE_SUCCESS = "CHAT/UPDATE_GROUP_IMAGE_SUCCESS";

export const UPDATE_GROUP_SUCCESS = "CHAT/UPDATE_GROUP_SUCCESS";

export const CONVERSATION_REPLY = "CHAT/CONVERSATION_REPLY";
export const CONVERSATION_REPLY_SUCCESS = "CHAT/CONVERSATION_REPLY_SUCCESS";

export const SET_SEEN_MESSAGES = "CHAT/SET_SEEN_MESSAGES";
export const SET_SEEN_MESSAGES_SUCCESS = "CHAT/SET_SEEN_MESSAGES_SUCCESS";

export const MUTE_CONVERSATION = "CHAT/MUTE_CONVERSATION";
export const MUTE_CONVERSATION_SUCCESS = "CHAT/MUTE_CONVERSATION_SUCCESS";

export const REFRESH_CONVERSATION = "CHAT/REFRESH_CONVERSATION";

export const CLEAR_SENT_MESSAGE = "CHAT/CLEAR_SENT_MESSAGE";

export const DELETE_CONVERSATION = "CHAT/DELETE_CONVERSATION";
export const DELETE_CONVERSATION_SUCCESS = "CHAT/DELETE_CONVERSATION_SUCCESS";
export const DELETE_MESSAGE_SUCCESS = "CHAT/DELETE_MESSAGE_SUCCESS";

export const EXIT_CONVERSATION = "CHAT/EXIT_CONVERSATION";
export const EXIT_CONVERSATION_SUCCESS = "CHAT/EXIT_CONVERSATION_SUCCESS";
